export const SCORING_WEIGHTS = {
  REQUIRED_SKILLS: 30,
  PREFERRED_SKILLS: 10,
  TOOLS: 10,
  EXPERIENCE: 25,
  EDUCATION: 15,
  ELIGIBILITY: 10,
  JOB_REALITY: 0,
  COMPETITION: 0,
} as const;

export const DECISION_THRESHOLDS = {
  PASS: 70,
  IMPROVE: 35,
  // Below 35 is REJECT
} as const;
